import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@splitflow/css-reset'
import { createSplitflowAppKit, loadSplitflowAppBundle } from '@splitflow/app'
import '@splitflow/css-reset/index.css'
import { SplitflowAppProvider, SsrRegistryProvider } from '@/lib/contexts'
import './globals.css'
import { appConfig } from '@/lib/configs'
import { firstError } from '@splitflow/lib'
import { Light } from '@/lib/components/Light'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const app = createSplitflowAppKit(appConfig)
    const bundle = await loadSplitflowAppBundle(app)

    const error = firstError(bundle)
    if (error) throw error

    return (
        <html lang="en">
            <body className={'sf-css-reset ' + inter.className}>
                <SsrRegistryProvider>
                    <SplitflowAppProvider bundle={bundle}>
                        <Light>{children}</Light>
                    </SplitflowAppProvider>
                </SsrRegistryProvider>
            </body>
        </html>
    )
}
